export const ADD_EXPENSE = 'ADD_EXPENSE';
export const UPDATE_TOTAL = 'UPDATE_TOTAL';
export const CURRENCY_FETCH = 'CURRENCY_FETCH';
export const USER_EMAIL = 'USER_EMAIL';
export const DELETE_EXPENSE = 'DELETE_EXPENSE';
